version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      #- MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=test_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "dev_phpmyadmin"
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      #- PMA_USER=root
      #- PMA_PASSWORD=
      - PMA_PORTS=3306 